from __future__ import annotations

from copy import deepcopy
from typing import Any

BASELINE_REVISION = "20260718_0001"

# Frozen from the UPGRADE_SQL contract in 20260718_0001_schema_baseline.py.
# Do not replace this with live Base.metadata: later model changes require a new migration.
_BASELINE_SCHEMA: dict[str, dict[str, Any]] = {'ai_care_summaries': {'columns': {'care_summary_id': {'type': 'uuid', 'nullable': False},
                                   'care_episode_id': {'type': 'uuid', 'nullable': False},
                                   'relationship_id': {'type': 'uuid', 'nullable': False},
                                   'conversation_digest': {'type': 'text', 'nullable': False},
                                   'plan_digest': {'type': 'text', 'nullable': False},
                                   'unresolved_questions': {'type': 'jsonb', 'nullable': False},
                                   'raw_score_trend': {'type': 'jsonb', 'nullable': True},
                                   'created_at': {'type': 'timestamp with time zone',
                                                  'nullable': False}},
                       'primary_key': ('care_summary_id',),
                       'foreign_keys': ((('care_episode_id',),
                                         'care_episodes',
                                         ('care_episode_id',),
                                         'cascade'),
                                        (('relationship_id',),
                                         'care_relationships',
                                         ('relationship_id',),
                                         'cascade')),
                       'unique_constraints': (),
                       'indexes': (('ix_ai_care_summaries_care_episode_id',
                                    ('care_episode_id',),
                                    False,
                                    None),
                                   ('ix_ai_care_summaries_relationship_id',
                                    ('relationship_id',),
                                    False,
                                    None))},
 'ai_daily_rehab_lists': {'columns': {'list_id': {'type': 'uuid', 'nullable': False},
                                      'care_episode_id': {'type': 'uuid', 'nullable': False},
                                      'patient_id': {'type': 'uuid', 'nullable': False},
                                      'source_recommendation_id': {'type': 'uuid',
                                                                   'nullable': True},
                                      'items': {'type': 'jsonb', 'nullable': False},
                                      'created_at': {'type': 'timestamp with time zone',
                                                     'nullable': False},
                                      'updated_at': {'type': 'timestamp with time zone',
                                                     'nullable': False}},
                          'primary_key': ('list_id',),
                          'foreign_keys': ((('care_episode_id',),
                                            'care_episodes',
                                            ('care_episode_id',),
                                            'cascade'),
                                           (('patient_id',),
                                            'patients',
                                            ('patient_id',),
                                            'cascade'),
                                           (('source_recommendation_id',),
                                            'ai_daily_rehab_recommendations',
                                            ('recommendation_id',),
                                            'set null')),
                          'unique_constraints': (('care_episode_id',),),
                          'indexes': (('ix_ai_daily_rehab_lists_care_episode_id',
                                       ('care_episode_id',),
                                       False,
                                       None),
                                      ('ix_ai_daily_rehab_lists_patient_id',
                                       ('patient_id',),
                                       False,
                                       None))},
 'ai_daily_rehab_recommendations': {'columns': {'recommendation_id': {'type': 'uuid',
                                                                      'nullable': False},
                                                'care_episode_id': {'type': 'uuid',
                                                                    'nullable': False},
                                                'patient_id': {'type': 'uuid', 'nullable': False},
                                                'source_triage_summary_id': {'type': 'uuid',
                                                                             'nullable': True},
                                                'source_triage_summary_version': {'type': 'integer',
                                                                                  'nullable': False},
                                                'status': {'type': 'varchar(32)',
                                                           'nullable': False},
                                                'empty_reason': {'type': 'text', 'nullable': False},
                                                'query_text': {'type': 'text', 'nullable': False},
                                                'items': {'type': 'jsonb', 'nullable': False},
                                                'active': {'type': 'boolean', 'nullable': False},
                                                'created_at': {'type': 'timestamp with time zone',
                                                               'nullable': False},
                                                'updated_at': {'type': 'timestamp with time zone',
                                                               'nullable': False}},
                                    'primary_key': ('recommendation_id',),
                                    'foreign_keys': ((('care_episode_id',),
                                                      'care_episodes',
                                                      ('care_episode_id',),
                                                      'cascade'),
                                                     (('patient_id',),
                                                      'patients',
                                                      ('patient_id',),
                                                      'cascade'),
                                                     (('source_triage_summary_id',),
                                                      'care_episode_triage_summaries',
                                                      ('triage_summary_id',),
                                                      'set null')),
                                    'unique_constraints': (),
                                    'indexes': (('ix_ai_daily_rehab_recommendations_care_episode_id',
                                                 ('care_episode_id',),
                                                 False,
                                                 None),
                                                ('ix_ai_daily_rehab_recommendations_patient_id',
                                                 ('patient_id',),
                                                 False,
                                                 None),
                                                ('ix_ai_daily_rehab_recommendations_source_triage_summary_id',
                                                 ('source_triage_summary_id',),
                                                 False,
                                                 None))},
 'ai_internal_messages': {'columns': {'internal_message_id': {'type': 'uuid', 'nullable': False},
                                      'session_id': {'type': 'uuid', 'nullable': True},
                                      'patient_id': {'type': 'uuid', 'nullable': True},
                                      'agent_name': {'type': 'varchar(64)', 'nullable': False},
                                      'event_type': {'type': 'varchar(64)', 'nullable': False},
                                      'content': {'type': 'text', 'nullable': False},
                                      'metadata': {'type': 'jsonb', 'nullable': False},
                                      'created_at': {'type': 'timestamp with time zone',
                                                     'nullable': False}},
                          'primary_key': ('internal_message_id',),
                          'foreign_keys': ((('patient_id',),
                                            'patients',
                                            ('patient_id',),
                                            'cascade'),
                                           (('session_id',),
                                            'ai_sessions',
                                            ('session_id',),
                                            'cascade')),
                          'unique_constraints': (),
                          'indexes': (('ix_ai_internal_messages_patient_id',
                                       ('patient_id',),
                                       False,
                                       None),
                                      ('ix_ai_internal_messages_session_id',
                                       ('session_id',),
                                       False,
                                       None))},
 'ai_messages': {'columns': {'message_id': {'type': 'uuid', 'nullable': False},
                             'session_id': {'type': 'uuid', 'nullable': False},
                             'sender_role': {'type': 'varchar(32)', 'nullable': False},
                             'content': {'type': 'text', 'nullable': False},
                             'created_at': {'type': 'timestamp with time zone', 'nullable': False}},
                 'primary_key': ('message_id',),
                 'foreign_keys': ((('session_id',), 'ai_sessions', ('session_id',), 'cascade'),),
                 'unique_constraints': (),
                 'indexes': ()},
 'ai_sessions': {'columns': {'session_id': {'type': 'uuid', 'nullable': False},
                             'patient_id': {'type': 'uuid', 'nullable': False},
                             'title': {'type': 'varchar(255)', 'nullable': False},
                             'created_at': {'type': 'timestamp with time zone', 'nullable': False},
                             'updated_at': {'type': 'timestamp with time zone', 'nullable': False}},
                 'primary_key': ('session_id',),
                 'foreign_keys': ((('patient_id',), 'patients', ('patient_id',), 'cascade'),),
                 'unique_constraints': (),
                 'indexes': ()},
 'care_appointments': {'columns': {'appointment_id': {'type': 'uuid', 'nullable': False},
                                   'relationship_id': {'type': 'uuid', 'nullable': False},
                                   'care_episode_id': {'type': 'uuid', 'nullable': True},
                                   'patient_id': {'type': 'uuid', 'nullable': False},
                                   'doctor_id': {'type': 'uuid', 'nullable': False},
                                   'scheduled_start': {'type': 'timestamp with time zone',
                                                       'nullable': False},
                                   'scheduled_end': {'type': 'timestamp with time zone',
                                                     'nullable': True},
                                   'status': {'type': 'varchar(32)', 'nullable': False},
                                   'purpose': {'type': 'text', 'nullable': False},
                                   'created_at': {'type': 'timestamp with time zone',
                                                  'nullable': False},
                                   'updated_at': {'type': 'timestamp with time zone',
                                                  'nullable': False}},
                       'primary_key': ('appointment_id',),
                       'foreign_keys': ((('care_episode_id',),
                                         'care_episodes',
                                         ('care_episode_id',),
                                         'set null'),
                                        (('doctor_id',), 'doctors', ('doctor_id',), 'cascade'),
                                        (('patient_id',), 'patients', ('patient_id',), 'cascade'),
                                        (('relationship_id',),
                                         'care_relationships',
                                         ('relationship_id',),
                                         'cascade')),
                       'unique_constraints': (),
                       'indexes': (('ix_care_appointments_care_episode_id',
                                    ('care_episode_id',),
                                    False,
                                    None),
                                   ('ix_care_appointments_doctor_id', ('doctor_id',), False, None),
                                   ('ix_care_appointments_patient_id',
                                    ('patient_id',),
                                    False,
                                    None),
                                   ('ix_care_appointments_relationship_id',
                                    ('relationship_id',),
                                    False,
                                    None),
                                   ('ix_care_appointments_scheduled_start',
                                    ('scheduled_start',),
                                    False,
                                    None))},
 'care_connection_requests': {'columns': {'request_id': {'type': 'uuid', 'nullable': False},
                                          'care_episode_id': {'type': 'uuid', 'nullable': False},
                                          'patient_id': {'type': 'uuid', 'nullable': False},
                                          'doctor_id': {'type': 'uuid', 'nullable': False},
                                          'request_reason': {'type': 'text', 'nullable': False},
                                          'status': {'type': 'varchar(32)', 'nullable': False},
                                          'responded_at': {'type': 'timestamp with time zone',
                                                           'nullable': True},
                                          'created_at': {'type': 'timestamp with time zone',
                                                         'nullable': False},
                                          'updated_at': {'type': 'timestamp with time zone',
                                                         'nullable': False}},
                              'primary_key': ('request_id',),
                              'foreign_keys': ((('care_episode_id',),
                                                'care_episodes',
                                                ('care_episode_id',),
                                                'cascade'),
                                               (('doctor_id',),
                                                'doctors',
                                                ('doctor_id',),
                                                'cascade'),
                                               (('patient_id',),
                                                'patients',
                                                ('patient_id',),
                                                'cascade')),
                              'unique_constraints': (('care_episode_id', 'doctor_id'),),
                              'indexes': (('ix_care_connection_requests_care_episode_id',
                                           ('care_episode_id',),
                                           False,
                                           None),
                                          ('ix_care_connection_requests_doctor_id',
                                           ('doctor_id',),
                                           False,
                                           None),
                                          ('ix_care_connection_requests_patient_id',
                                           ('patient_id',),
                                           False,
                                           None))},
 'care_conversation_messages': {'columns': {'message_id': {'type': 'uuid', 'nullable': False},
                                            'care_episode_id': {'type': 'uuid', 'nullable': False},
                                            'relationship_id': {'type': 'uuid', 'nullable': False},
                                            'sender_id': {'type': 'uuid', 'nullable': False},
                                            'sender_role': {'type': 'varchar(32)',
                                                            'nullable': False},
                                            'content': {'type': 'text', 'nullable': False},
                                            'created_at': {'type': 'timestamp with time zone',
                                                           'nullable': False}},
                                'primary_key': ('message_id',),
                                'foreign_keys': ((('care_episode_id',),
                                                  'care_episodes',
                                                  ('care_episode_id',),
                                                  'cascade'),
                                                 (('relationship_id',),
                                                  'care_relationships',
                                                  ('relationship_id',),
                                                  'cascade')),
                                'unique_constraints': (),
                                'indexes': (('ix_care_conversation_messages_care_episode_id',
                                             ('care_episode_id',),
                                             False,
                                             None),
                                            ('ix_care_conversation_messages_relationship_id',
                                             ('relationship_id',),
                                             False,
                                             None))},
 'care_episode_triage_summaries': {'columns': {'triage_summary_id': {'type': 'uuid',
                                                                     'nullable': False},
                                               'care_episode_id': {'type': 'uuid',
                                                                   'nullable': False},
                                               'patient_id': {'type': 'uuid', 'nullable': False},
                                               'version': {'type': 'integer', 'nullable': False},
                                               'concern': {'type': 'varchar(255)',
                                                           'nullable': False},
                                               'relevant_context': {'type': 'text',
                                                                    'nullable': False},
                                               'safety_signals': {'type': 'jsonb',
                                                                  'nullable': False},
                                               'limitations': {'type': 'jsonb', 'nullable': False},
                                               'recommendation': {'type': 'text',
                                                                  'nullable': False},
                                               'missing_information': {'type': 'jsonb',
                                                                       'nullable': False},
                                               'unresolved_questions': {'type': 'jsonb',
                                                                        'nullable': False},
                                               'clinician_review_needed': {'type': 'boolean',
                                                                           'nullable': False},
                                               'additional_context': {'type': 'text',
                                                                      'nullable': False},
                                               'source_ai_session_id': {'type': 'uuid',
                                                                        'nullable': True},
                                               'source_conversation_transcript': {'type': 'text',
                                                                                  'nullable': False},
                                               'created_at': {'type': 'timestamp with time zone',
                                                              'nullable': False}},
                                   'primary_key': ('triage_summary_id',),
                                   'foreign_keys': ((('care_episode_id',),
                                                     'care_episodes',
                                                     ('care_episode_id',),
                                                     'cascade'),
                                                    (('patient_id',),
                                                     'patients',
                                                     ('patient_id',),
                                                     'cascade'),
                                                    (('source_ai_session_id',),
                                                     'ai_sessions',
                                                     ('session_id',),
                                                     'set null')),
                                   'unique_constraints': (('care_episode_id', 'version'),),
                                   'indexes': (('ix_care_episode_triage_summaries_care_episode_id',
                                                ('care_episode_id',),
                                                False,
                                                None),
                                               ('ix_care_episode_triage_summaries_patient_id',
                                                ('patient_id',),
                                                False,
                                                None))},
 'care_episode_triage_summary_drafts': {'columns': {'triage_summary_draft_id': {'type': 'uuid',
                                                                                'nullable': False},
                                                    'care_episode_id': {'type': 'uuid',
                                                                        'nullable': False},
                                                    'patient_id': {'type': 'uuid',
                                                                   'nullable': False},
                                                    'concern': {'type': 'varchar(255)',
                                                                'nullable': False},
                                                    'relevant_context': {'type': 'text',
                                                                         'nullable': False},
                                                    'safety_signals': {'type': 'jsonb',
                                                                       'nullable': False},
                                                    'limitations': {'type': 'jsonb',
                                                                    'nullable': False},
                                                    'recommendation': {'type': 'text',
                                                                       'nullable': False},
                                                    'missing_information': {'type': 'jsonb',
                                                                            'nullable': False},
                                                    'unresolved_questions': {'type': 'jsonb',
                                                                             'nullable': False},
                                                    'clinician_review_needed': {'type': 'boolean',
                                                                                'nullable': False},
                                                    'additional_context': {'type': 'text',
                                                                           'nullable': False},
                                                    'source_ai_session_id': {'type': 'uuid',
                                                                             'nullable': True},
                                                    'source_conversation_transcript': {'type': 'text',
                                                                                       'nullable': False},
                                                    'created_at': {'type': 'timestamp with time '
                                                                           'zone',
                                                                   'nullable': False}},
                                        'primary_key': ('triage_summary_draft_id',),
                                        'foreign_keys': ((('care_episode_id',),
                                                          'care_episodes',
                                                          ('care_episode_id',),
                                                          'cascade'),
                                                         (('patient_id',),
                                                          'patients',
                                                          ('patient_id',),
                                                          'cascade'),
                                                         (('source_ai_session_id',),
                                                          'ai_sessions',
                                                          ('session_id',),
                                                          'set null')),
                                        'unique_constraints': (),
                                        'indexes': (('ix_care_episode_triage_summary_drafts_care_episode_id',
                                                     ('care_episode_id',),
                                                     False,
                                                     None),
                                                    ('ix_care_episode_triage_summary_drafts_patient_id',
                                                     ('patient_id',),
                                                     False,
                                                     None))},
 'care_episodes': {'columns': {'care_episode_id': {'type': 'uuid', 'nullable': False},
                               'patient_id': {'type': 'uuid', 'nullable': False},
                               'issue_title': {'type': 'varchar(255)', 'nullable': False},
                               'body_area': {'type': 'varchar(128)', 'nullable': False},
                               'goal': {'type': 'varchar(255)', 'nullable': False},
                               'short_description': {'type': 'text', 'nullable': False},
                               'symptom_started_on': {'type': 'date', 'nullable': True},
                               'origin': {'type': 'varchar(32)', 'nullable': False},
                               'safety_gate_status': {'type': 'varchar(64)', 'nullable': False},
                               'status': {'type': 'varchar(32)', 'nullable': False},
                               'selected_doctor_id': {'type': 'uuid', 'nullable': True},
                               'latest_triage_summary': {'type': 'jsonb', 'nullable': True},
                               'created_at': {'type': 'timestamp with time zone',
                                              'nullable': False},
                               'updated_at': {'type': 'timestamp with time zone',
                                              'nullable': False}},
                   'primary_key': ('care_episode_id',),
                   'foreign_keys': ((('patient_id',), 'patients', ('patient_id',), 'cascade'),
                                    (('selected_doctor_id',),
                                     'doctors',
                                     ('doctor_id',),
                                     'set null')),
                   'unique_constraints': (),
                   'indexes': (('ix_care_episodes_patient_id', ('patient_id',), False, None),)},
 'care_relationships': {'columns': {'relationship_id': {'type': 'uuid', 'nullable': False},
                                    'care_episode_id': {'type': 'uuid', 'nullable': False},
                                    'patient_id': {'type': 'uuid', 'nullable': False},
                                    'doctor_id': {'type': 'uuid', 'nullable': False},
                                    'source_request_id': {'type': 'uuid', 'nullable': False},
                                    'status': {'type': 'varchar(32)', 'nullable': False},
                                    'created_at': {'type': 'timestamp with time zone',
                                                   'nullable': False},
                                    'updated_at': {'type': 'timestamp with time zone',
                                                   'nullable': False}},
                        'primary_key': ('relationship_id',),
                        'foreign_keys': ((('care_episode_id',),
                                          'care_episodes',
                                          ('care_episode_id',),
                                          'cascade'),
                                         (('doctor_id',), 'doctors', ('doctor_id',), 'cascade'),
                                         (('patient_id',), 'patients', ('patient_id',), 'cascade'),
                                         (('source_request_id',),
                                          'care_connection_requests',
                                          ('request_id',),
                                          'cascade')),
                        'unique_constraints': (('care_episode_id',),),
                        'indexes': (('ix_care_relationships_care_episode_id',
                                     ('care_episode_id',),
                                     False,
                                     None),
                                    ('ix_care_relationships_doctor_id',
                                     ('doctor_id',),
                                     False,
                                     None),
                                    ('ix_care_relationships_patient_id',
                                     ('patient_id',),
                                     False,
                                     None))},
 'consultation_messages': {'columns': {'message_id': {'type': 'uuid', 'nullable': False},
                                       'thread_id': {'type': 'uuid', 'nullable': False},
                                       'sender_id': {'type': 'uuid', 'nullable': False},
                                       'content': {'type': 'text', 'nullable': False},
                                       'read_receipt': {'type': 'boolean', 'nullable': False},
                                       'created_at': {'type': 'timestamp with time zone',
                                                      'nullable': False}},
                           'primary_key': ('message_id',),
                           'foreign_keys': ((('thread_id',),
                                             'consultation_threads',
                                             ('thread_id',),
                                             'cascade'),),
                           'unique_constraints': (),
                           'indexes': ()},
 'consultation_threads': {'columns': {'thread_id': {'type': 'uuid', 'nullable': False},
                                      'patient_id': {'type': 'uuid', 'nullable': False},
                                      'doctor_id': {'type': 'uuid', 'nullable': False},
                                      'status': {'type': 'varchar(32)', 'nullable': False},
                                      'created_at': {'type': 'timestamp with time zone',
                                                     'nullable': False},
                                      'updated_at': {'type': 'timestamp with time zone',
                                                     'nullable': False}},
                          'primary_key': ('thread_id',),
                          'foreign_keys': ((('doctor_id',), 'doctors', ('doctor_id',), 'cascade'),
                                           (('patient_id',),
                                            'patients',
                                            ('patient_id',),
                                            'cascade')),
                          'unique_constraints': (),
                          'indexes': ()},
 'doctor_intelligence_artifacts': {'columns': {'artifact_id': {'type': 'uuid', 'nullable': False},
                                               'doctor_id': {'type': 'uuid', 'nullable': False},
                                               'artifact_type': {'type': 'varchar(64)',
                                                                 'nullable': False},
                                               'title': {'type': 'varchar(255)', 'nullable': False},
                                               'content': {'type': 'text', 'nullable': False},
                                               'sections': {'type': 'jsonb', 'nullable': False},
                                               'attention_map': {'type': 'jsonb',
                                                                 'nullable': False},
                                               'input_refs': {'type': 'jsonb', 'nullable': False},
                                               'visibility': {'type': 'varchar(64)',
                                                              'nullable': False},
                                               'version': {'type': 'integer', 'nullable': False},
                                               'status': {'type': 'varchar(32)', 'nullable': False},
                                               'created_at': {'type': 'timestamp with time zone',
                                                              'nullable': False},
                                               'updated_at': {'type': 'timestamp with time zone',
                                                              'nullable': False}},
                                   'primary_key': ('artifact_id',),
                                   'foreign_keys': ((('doctor_id',),
                                                     'doctors',
                                                     ('doctor_id',),
                                                     'cascade'),),
                                   'unique_constraints': (),
                                   'indexes': (('ix_doctor_intelligence_artifacts_artifact_type',
                                                ('artifact_type',),
                                                False,
                                                None),
                                               ('ix_doctor_intelligence_artifacts_doctor_id',
                                                ('doctor_id',),
                                                False,
                                                None))},
 'doctors': {'columns': {'doctor_id': {'type': 'uuid', 'nullable': False},
                         'doctor_name': {'type': 'varchar(255)', 'nullable': False},
                         'password_hash': {'type': 'varchar(512)', 'nullable': False},
                         'real_info': {'type': 'jsonb', 'nullable': False},
                         'verification_status': {'type': 'varchar(64)', 'nullable': False},
                         'created_at': {'type': 'timestamp with time zone', 'nullable': False},
                         'updated_at': {'type': 'timestamp with time zone', 'nullable': False}},
             'primary_key': ('doctor_id',),
             'foreign_keys': (),
             'unique_constraints': (('doctor_name',),),
             'indexes': ()},
 'episode_rehab_sessions': {'columns': {'session_id': {'type': 'uuid', 'nullable': False},
                                        'care_episode_id': {'type': 'uuid', 'nullable': False},
                                        'patient_id': {'type': 'uuid', 'nullable': False},
                                        'recommended_exercises': {'type': 'jsonb',
                                                                  'nullable': False},
                                        'checklist': {'type': 'jsonb', 'nullable': False},
                                        'patient_notes': {'type': 'text', 'nullable': False},
                                        'session_summary': {'type': 'text', 'nullable': False},
                                        'completion_status': {'type': 'varchar(32)',
                                                              'nullable': False},
                                        'created_at': {'type': 'timestamp with time zone',
                                                       'nullable': False},
                                        'updated_at': {'type': 'timestamp with time zone',
                                                       'nullable': False}},
                            'primary_key': ('session_id',),
                            'foreign_keys': ((('care_episode_id',),
                                              'care_episodes',
                                              ('care_episode_id',),
                                              'cascade'),
                                             (('patient_id',),
                                              'patients',
                                              ('patient_id',),
                                              'cascade')),
                            'unique_constraints': (),
                            'indexes': (('ix_episode_rehab_sessions_care_episode_id',
                                         ('care_episode_id',),
                                         False,
                                         None),
                                        ('ix_episode_rehab_sessions_patient_id',
                                         ('patient_id',),
                                         False,
                                         None))},
 'memory_agent_runs': {'columns': {'run_id': {'type': 'uuid', 'nullable': False},
                                   'patient_id': {'type': 'uuid', 'nullable': False},
                                   'care_episode_id': {'type': 'uuid', 'nullable': True},
                                   'trigger': {'type': 'varchar(64)', 'nullable': False},
                                   'status': {'type': 'varchar(32)', 'nullable': False},
                                   'changes': {'type': 'jsonb', 'nullable': False},
                                   'metadata': {'type': 'jsonb', 'nullable': False},
                                   'created_at': {'type': 'timestamp with time zone',
                                                  'nullable': False},
                                   'updated_at': {'type': 'timestamp with time zone',
                                                  'nullable': False}},
                       'primary_key': ('run_id',),
                       'foreign_keys': ((('care_episode_id',),
                                         'care_episodes',
                                         ('care_episode_id',),
                                         'cascade'),
                                        (('patient_id',), 'patients', ('patient_id',), 'cascade')),
                       'unique_constraints': (),
                       'indexes': (('ix_memory_agent_runs_care_episode_id',
                                    ('care_episode_id',),
                                    False,
                                    None),
                                   ('ix_memory_agent_runs_patient_id',
                                    ('patient_id',),
                                    False,
                                    None))},
 'memory_document_items': {'columns': {'memory_item_id': {'type': 'uuid', 'nullable': False},
                                       'document_id': {'type': 'uuid', 'nullable': False},
                                       'item_type': {'type': 'varchar(64)', 'nullable': False},
                                       'title': {'type': 'varchar(255)', 'nullable': False},
                                       'content': {'type': 'text', 'nullable': False},
                                       'status': {'type': 'varchar(32)', 'nullable': False},
                                       'visibility': {'type': 'varchar(64)', 'nullable': False},
                                       'source_type': {'type': 'varchar(64)', 'nullable': False},
                                       'source_id': {'type': 'text', 'nullable': True},
                                       'evidence': {'type': 'jsonb', 'nullable': False},
                                       'reason': {'type': 'text', 'nullable': False},
                                       'archived_at': {'type': 'timestamp with time zone',
                                                       'nullable': True},
                                       'created_at': {'type': 'timestamp with time zone',
                                                      'nullable': False},
                                       'updated_at': {'type': 'timestamp with time zone',
                                                      'nullable': False}},
                           'primary_key': ('memory_item_id',),
                           'foreign_keys': ((('document_id',),
                                             'memory_documents',
                                             ('document_id',),
                                             'cascade'),),
                           'unique_constraints': (),
                           'indexes': (('ix_memory_document_items_document_id',
                                        ('document_id',),
                                        False,
                                        None),)},
 'memory_documents': {'columns': {'document_id': {'type': 'uuid', 'nullable': False},
                                  'scope': {'type': 'varchar(32)', 'nullable': False},
                                  'patient_id': {'type': 'uuid', 'nullable': False},
                                  'care_episode_id': {'type': 'uuid', 'nullable': True},
                                  'compiled_text': {'type': 'text', 'nullable': False},
                                  'status': {'type': 'varchar(32)', 'nullable': False},
                                  'last_compiled_at': {'type': 'timestamp with time zone',
                                                       'nullable': True},
                                  'created_at': {'type': 'timestamp with time zone',
                                                 'nullable': False},
                                  'updated_at': {'type': 'timestamp with time zone',
                                                 'nullable': False}},
                      'primary_key': ('document_id',),
                      'foreign_keys': ((('care_episode_id',),
                                        'care_episodes',
                                        ('care_episode_id',),
                                        'cascade'),
                                       (('patient_id',), 'patients', ('patient_id',), 'cascade')),
                      'unique_constraints': (),
                      'indexes': (('ix_memory_documents_care_episode_id',
                                   ('care_episode_id',),
                                   False,
                                   None),
                                  ('ix_memory_documents_patient_id', ('patient_id',), False, None),
                                  ('ix_memory_documents_scope', ('scope',), False, None),
                                  ('uq_memory_documents_episode_document',
                                   ('care_episode_id',),
                                   True,
                                   "scope = 'episode' and care_episode_id is not null"),
                                  ('uq_memory_documents_patient_document',
                                   ('patient_id',),
                                   True,
                                   "scope = 'patient' and care_episode_id is null"))},
 'patient_clinical_memory': {'columns': {'memory_id': {'type': 'uuid', 'nullable': False},
                                         'patient_id': {'type': 'uuid', 'nullable': False},
                                         'fact_category': {'type': 'varchar(64)',
                                                           'nullable': False},
                                         'extracted_fact': {'type': 'text', 'nullable': False},
                                         'source_session_id': {'type': 'uuid', 'nullable': True},
                                         'created_at': {'type': 'timestamp with time zone',
                                                        'nullable': False},
                                         'updated_at': {'type': 'timestamp with time zone',
                                                        'nullable': False}},
                             'primary_key': ('memory_id',),
                             'foreign_keys': ((('patient_id',),
                                               'patients',
                                               ('patient_id',),
                                               'cascade'),
                                              (('source_session_id',),
                                               'ai_sessions',
                                               ('session_id',),
                                               'set null')),
                             'unique_constraints': (),
                             'indexes': ()},
 'patient_clinical_records': {'columns': {'record_id': {'type': 'uuid', 'nullable': False},
                                          'patient_id': {'type': 'uuid', 'nullable': False},
                                          'generated_by_ai': {'type': 'boolean', 'nullable': False},
                                          'doctor_reviewer_id': {'type': 'uuid', 'nullable': True},
                                          'detailed_content': {'type': 'jsonb', 'nullable': False},
                                          'updated_time': {'type': 'timestamp with time zone',
                                                           'nullable': False}},
                              'primary_key': ('record_id',),
                              'foreign_keys': ((('doctor_reviewer_id',),
                                                'doctors',
                                                ('doctor_id',),
                                                'set null'),
                                               (('patient_id',),
                                                'patients',
                                                ('patient_id',),
                                                'cascade')),
                              'unique_constraints': (),
                              'indexes': ()},
 'patient_doctor_mappings': {'columns': {'mapping_id': {'type': 'uuid', 'nullable': False},
                                         'patient_id': {'type': 'uuid', 'nullable': False},
                                         'doctor_id': {'type': 'uuid', 'nullable': False},
                                         'status': {'type': 'varchar(32)', 'nullable': False},
                                         'created_at': {'type': 'timestamp with time zone',
                                                        'nullable': False},
                                         'updated_at': {'type': 'timestamp with time zone',
                                                        'nullable': False}},
                             'primary_key': ('mapping_id',),
                             'foreign_keys': ((('doctor_id',),
                                               'doctors',
                                               ('doctor_id',),
                                               'cascade'),
                                              (('patient_id',),
                                               'patients',
                                               ('patient_id',),
                                               'cascade')),
                             'unique_constraints': (('patient_id', 'doctor_id'),),
                             'indexes': ()},
 'patients': {'columns': {'patient_id': {'type': 'uuid', 'nullable': False},
                          'patient_name': {'type': 'varchar(255)', 'nullable': False},
                          'password_hash': {'type': 'varchar(512)', 'nullable': False},
                          'real_info': {'type': 'jsonb', 'nullable': False},
                          'subscription_tier': {'type': 'varchar(64)', 'nullable': False},
                          'created_at': {'type': 'timestamp with time zone', 'nullable': False},
                          'updated_at': {'type': 'timestamp with time zone', 'nullable': False}},
              'primary_key': ('patient_id',),
              'foreign_keys': (),
              'unique_constraints': (('patient_name',),),
              'indexes': ()},
 'rehab_exercise_videos': {'columns': {'exercise_id': {'type': 'uuid', 'nullable': False},
                                       'slug': {'type': 'varchar(255)', 'nullable': False},
                                       'title': {'type': 'varchar(255)', 'nullable': False},
                                       'source_url': {'type': 'text', 'nullable': False},
                                       'video_url': {'type': 'text', 'nullable': False},
                                       'local_video_path': {'type': 'text', 'nullable': True},
                                       'public_video_url': {'type': 'text', 'nullable': True},
                                       'demo_profile': {'type': 'varchar(128)', 'nullable': False},
                                       'relevance_rank': {'type': 'integer', 'nullable': False},
                                       'relevance_score': {'type': 'integer', 'nullable': False},
                                       'relevance_notes': {'type': 'text', 'nullable': False},
                                       'download_status': {'type': 'varchar(32)',
                                                           'nullable': False},
                                       'pose_status': {'type': 'varchar(32)', 'nullable': False},
                                       'exercise_metadata': {'type': 'jsonb', 'nullable': False},
                                       'created_at': {'type': 'timestamp with time zone',
                                                      'nullable': False},
                                       'updated_at': {'type': 'timestamp with time zone',
                                                      'nullable': False}},
                           'primary_key': ('exercise_id',),
                           'foreign_keys': (),
                           'unique_constraints': (),
                           'indexes': (('ix_rehab_exercise_videos_slug', ('slug',), True, None),)},
 'rehab_plans': {'columns': {'plan_id': {'type': 'uuid', 'nullable': False},
                             'patient_id': {'type': 'uuid', 'nullable': False},
                             'doctor_id': {'type': 'uuid', 'nullable': True},
                             'state': {'type': 'varchar(32)', 'nullable': False},
                             'created_at': {'type': 'timestamp with time zone', 'nullable': False},
                             'updated_at': {'type': 'timestamp with time zone', 'nullable': False}},
                 'primary_key': ('plan_id',),
                 'foreign_keys': ((('doctor_id',), 'doctors', ('doctor_id',), 'set null'),
                                  (('patient_id',), 'patients', ('patient_id',), 'cascade')),
                 'unique_constraints': (),
                 'indexes': ()},
 'rehab_sessions': {'columns': {'session_id': {'type': 'uuid', 'nullable': False},
                                'plan_id': {'type': 'uuid', 'nullable': False},
                                'scheduled_time': {'type': 'timestamp with time zone',
                                                   'nullable': False},
                                'completion_status': {'type': 'varchar(32)', 'nullable': False},
                                'created_at': {'type': 'timestamp with time zone',
                                               'nullable': False},
                                'updated_at': {'type': 'timestamp with time zone',
                                               'nullable': False}},
                    'primary_key': ('session_id',),
                    'foreign_keys': ((('plan_id',), 'rehab_plans', ('plan_id',), 'cascade'),),
                    'unique_constraints': (),
                    'indexes': ()},
 'video_pose_extractions': {'columns': {'extraction_id': {'type': 'uuid', 'nullable': False},
                                        'exercise_id': {'type': 'uuid', 'nullable': False},
                                        'source_video_path': {'type': 'text', 'nullable': False},
                                        'frame_count': {'type': 'integer', 'nullable': False},
                                        'detected_frame_count': {'type': 'integer',
                                                                 'nullable': False},
                                        'fps': {'type': 'float', 'nullable': False},
                                        'duration_seconds': {'type': 'float', 'nullable': False},
                                        'detector_name': {'type': 'varchar(64)', 'nullable': False},
                                        'detector_version': {'type': 'varchar(64)',
                                                             'nullable': False},
                                        'pose_data': {'type': 'jsonb', 'nullable': False},
                                        'metrics': {'type': 'jsonb', 'nullable': False},
                                        'created_at': {'type': 'timestamp with time zone',
                                                       'nullable': False},
                                        'updated_at': {'type': 'timestamp with time zone',
                                                       'nullable': False}},
                            'primary_key': ('extraction_id',),
                            'foreign_keys': ((('exercise_id',),
                                              'rehab_exercise_videos',
                                              ('exercise_id',),
                                              'cascade'),),
                            'unique_constraints': (('exercise_id',),),
                            'indexes': ()}}

def baseline_schema_description() -> dict[str, dict[str, Any]]:
    return deepcopy(_BASELINE_SCHEMA)
